# Generated by Django 5.0.1 on 2024-01-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.films'),
        ),
    ]
