# Generated by Django 5.0.1 on 2024-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_poster_films'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='brith_year',
            new_name='birth_year',
        ),
    ]
